# -------------------------------------------
# 🌱 Spring Boot Application Configuration
# -------------------------------------------

# Application name (optional)
spring.application.name=petfull-backend

# -------------------------------------------
# ⚙️ Database Configuration (MongoDB)
# -------------------------------------------
spring.data.mongodb.uri=mongodb+srv://aviralgoel9th_db_user:HhBaLA3Td616vwxU@clusterpetfull.fhoggd6.mongodb.net/?appName=ClusterPetfull
spring.data.mongodb.database=petfull-db

# -------------------------------------------
# 🔥 Server Port (optional)
# -------------------------------------------
server.port=${PORT:8080}

